openapi: 3.0.2
info:
  title: IBM PlantExpert - OpenAPI 3.0
  description: |-
    This is a Plant Expert API using Watsonx AI 

    Some useful links:
    - [The PlantExpert repository](https://github.com/IBM-api/IBM-PlantExpert)
    - [The source API definition for the PlantExpert](https://github.com/IBM-api/IBM-PlantExpert/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://IBM.io/terms/
  contact:
    email: apiteam@IBM.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.15
  x-ibm-annotations: "true"
  x-ibm-application-name: WatsonX Plant Expert
  x-ibm-application-id: PlantExpert
  x-ibm-skill-type: imported
  x-ibm-application-icon: "<svg width=\"19\" height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xml:space=\"preserve\" overflow=\"hidden\"><defs><clipPath id=\"clip0\"><rect x=\"7\" y=\"370\" width=\"19\" height=\"20\"/></clipPath><image width=\"41\" height=\"42\" xlink:href=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QCMRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAACmgAwAEAAAAAQAAACoAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y8AsgTpgAmY7PhCfv/AABEIACoAKQMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2wBDAAICAgICAgMCAgMFAwMDBQYFBQUFBggGBgYGBggKCAgICAgICgoKCgoKCgoMDAwMDAwODg4ODg8PDw8PDw8PDw//2wBDAQICAgQEBAcEBAcQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/3QAEAAP/2gAMAwEAAhEDEQA/AP15vb230+A3Fy21RwB3J9BXG3/jGMadFPassTX15HYwueQruQHfng7AfzpuoW3iPVrm+vtP09LuG2zFbpKxVW2j53AHJJbj6CvMVuob7wjZW2q6XG2nfa7iKYRF457O6MhYlWYsMEEEAj2zXZRw6tdnbFXOh+Jdtq2h+IYYtJvLiBI8f8tGJc+rZPJJr0Xwprn2zXI/B+tttvbqzS9s5u7oVBkicdCyHkHqV68jJ43ULHWb+XS7fVLxdVh2boLhk2TNGnabnBK9yevqa4zTbu+1P4s2OqWt217fabFO5cIEt44kjYBSo9SQPvd+lb8inGz6IpR0PpW6tZrOUwzDnsexHqKrVlaP8QLHxPjSdRjW2vyN0LDISQ91GehPpnrWrmvMqU3F2Zmr9T//0P0l8X+HPEWjzNfaZI1zGfmidG42nkbSDxx0xXL2uua7OstidMjvV1NUe8RnEZebaAX3fwuABz65yOa9YSaexN3oy6m9ogy0MUwVoWV+QEdgSnuCcZ6Y6Vxj+HLWS2klW+RLm4Yjyw4MgA7YBzyec969SDTjqd8J3VmP0d3nt5NJupQ0lsnls0bh2SKYg7XYcBspgkZ47Cq9hJJo+srpFrpv2O1nJa5lzl5I0BYKGH8JI5xRoWmR+ELeeCUO8czM0kxBIyTkZPoOlU9Z8VfY7C5eyIuHVC0O35s+qjHPNSqd21EtnJat4gkTxAl4Iljjhb5fL6Lg5GMen4e1fRH9s3P9z9P/AK1eF/DTTdY8WTtqeu6Q+l2cLFv9JAEsgB4VEHIBPVm7dBnkfR+8+g/KlmFSKag9WjKVuh//0f1y1HTINQUGQfOnQ+3oa8/1fwsY7wXtmfKZgFfHUgf4ivUqa6I6kOoYe4zWuHxEoOx2bao8ObU9R06aSB4y0TcY6g/hXnfh/wAPXc+sXUdnbuUnmLqoy20ZyBzwB619IXEMLkho1I3AcgeldDb28FtCqW8axKRkhQFBP4V6MsX7OGi1Y5u5R0iwbT7RYpW3SH72Og9hWpRRXjSk27sR/9k=\" preserveAspectRatio=\"none\" id=\"img1\"></image><clipPath id=\"clip2\"><path d=\"M7 380C7 374.477 11.2533 370 16.5 370 21.7467 370 26 374.477 26 380 26 385.523 21.7467 390 16.5 390 11.2533 390 7 385.523 7 380Z\" fill-rule=\"evenodd\" clip-rule=\"evenodd\"/></clipPath></defs><g clip-path=\"url(#clip0)\" transform=\"translate(-7 -370)\"><g clip-path=\"url(#clip2)\"><use width=\"100%\" height=\"100%\" xlink:href=\"#img1\" opacity=\"1\" transform=\"matrix(0.463415 0 0 0.47619 7 370)\"></use></g></g></svg>"
servers:
- url: https://bs1lhv1m-8080.uks1.devtunnels.ms
security:
- basic_auth: []  
tags:
- name: plantexpert
  description: plantexpert
paths:
  /plantexpert:
    post:
      tags:
      - plantexpert
      summary: plantexpert
      description: Ask Question about plant growing conditions
      operationId: plantexpert
      parameters:
      - name: projectId
        in: query
        description: Project Identifier for classification
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: 902e9bda-956c-46af-ad1f-e6aeaaadd283
      - name: apiKey
        in: query
        description: Api Key
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: pXlFhgkg_wfJu2jvLrkNvboGEX4P0hyAX5vm4l8ulSda      
      requestBody:
        description: PlantExpert prompt
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "405":
          description: Invalid input
      x-swagger-router-controller: PlantExpert
components:
  schemas:
    Request:
      type: object
      properties:
        plant:
          type: string
          example: Cactus
    Response:
      type: object
      properties:
        generated:
          type: string
          example: "\n\n| Condition          | Value         |\n|--------------------|--------------|\n| Temperature range  | 10-18°C      |\n| Light              | Full sun     |\n| Humidity           | 60-70%       |\n| Watering level     | Medium       |"       
        lux:
          type: string
          example: 1000
        lightOn:
          type: number
          example: 8   
        lightOff:
          type: number
          example: 21    
        highTemp:
          type: number
          example: 25  
        lowTemp:
          type: number
          example: 25     
        highHumidity:
          type: number
          example: 80       
        lowHumidity:
          type: number
          example: 25     
        wateringDuration:
          type: number
          example: 2          
        waterTime1:
          type: number
          example: 8              
        waterTime2:
          type: number
          example: 8       
        waterTime3:
          type: number
          example: 8                                                                    

  securitySchemes:
    basic_auth:
      type: http
      scheme: basic