#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
# NOCACHE: set this to "--no-cache" to turn off the podman build cache
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `podman push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY=${REGISTRY:-docker.io/cloudcapped}

export EXT_REGISTRY=${EXT_REGISTRY:-icr.io/centc}

# Build the image
#podman build ${NOCACHE} -t ${REGISTRY}/plantai . --platform linux/amd64

# And push it to IBM cloud registry
podman push docker.io/cloudcapped/plantai ${EXT_REGISTRY}/plantai





